### ISSUE TITLE
Stop SessionTimeRemain from going down.

### ISSUE THREAD

**Issue by OutdatedDev** [OutdatedDev/iRacingRPC#1]
SessionTimeRemain aka total_time should remain at the time it started, for example: if qualifying doesnt have a lap limit and has a time limit of 8 minutes instead, it should show something like 00:06:21 of 00:08:00 as an example.
```python
                if total_laps in [None, "None", 0]:
                    if total_time in [None, "None", 604800] or state in ["Test", "Practice"]:
                        elapsed_time = time.strftime('%H:%M:%S', time.gmtime(elapsed_time))
                        statetext = f"{elapsed_time} | {lap_num} laps | {carname}"
                    else:
                        elapsed_time = time.strftime('%H:%M:%S', time.gmtime(elapsed_time))
                        total_time = time.strftime('%H:%M:%S', time.gmtime(total_time))
                        statetext = f"P{position} | {elapsed_time} of {total_time} | {carname}"
                else:
                    statetext = f"P{position} | {lap_num} of {total_laps} | {carname}"
```

**Comment by LyubomirT** [comment]
I'd like to take this issue on, please assign me to it.

**Comment by OutdatedDev** [comment]
Correction: What I meant to say was for timed sessions in general that use {elapsed_time} of {display_total_time}, not just qualifying.

For example: if there current session is a race, and instead of laps it has a limit of 12 minutes, it should stay at for example: 0:08:23 of 00:12:00
